//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkClassroom.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PhotosDBEntities : DbContext
    {
        public PhotosDBEntities()
            : base("name=PhotosDBEntities")
        {
            Comments = Set<Comments>();
            Photo = Set<Photo>();
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        internal virtual DbSet<Comments> Comments { get; set; }
        internal virtual DbSet<Photo> Photo { get; set; }

        public System.Data.Entity.DbSet<EntityFrameworkClassroom.Models.Photo> Photos { get; set; }
    }
}
